
export const storeProducts = [
  
  {
    id: 1,
    title: "Estelle Black Soap",
    img: "img/ebs.jpg",
    price: 3500,
    description: "Artisan made with antibacterial and antiseptic plant derived ingredients to smoothen the skin, enhance skin glow and radiance. Keeps your skin protected from acne and blemishes.",
    contains: "Aloe Barbadensis(aloe vera juice), Azaddirachta(Neem Leaf), African Black Soap, Cymbopogon Schoenanthus Extract(Lemon Grass), and Chamomile Recutiva.",
    usage: "Apply on whole body and rinse off with warm water.",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 2,
    title: "Light Radiance Lotion",
    img: "img/light radiance lotion.jpg",
    price: 7000,
    description: "Designed to brighten and lighten skin giving you an radiant flawless finish, and firms up the skin.",
    contains: "Rose Hydrosol, Grape Seed Oil, Arbutin, Frankincense Oil and Sandalwood Oil",
    usage: "Apply on damp skin",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    inCart: false,
    count: 0,
    total: 0
  },
  
  {
    id: 3,
    title: "Radiance Face Soap",
    img: "img/radiant face soap.jpg",
    price: 2500,
    description: "Specifically formulated to control oily skin, mildly exfoliates the face and control breakouts ",
    contains: "African black soap, Organic willowbark and Aloe vera ",
    usage: "Apply as desired on damp skin, then rise off with warm water",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 4,
    title: "Shea Glow Oil",
    img: "img/sgo.jpg",
    price: 2500,
    description: "Light and fast absorbing oil made as a long lasting moisturizer, softens the skin while improving skin radiance",
    contains: "Shea nut oil, Almond oil, Chamomile oil and Viamin E oil ",
    usage: "apply on whole body",
    life: "DO NOT USE, IF YOU HAVE NUT ALLERGIES!   Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 5,
    title: "Body Souffle",
    img: "img/body souffle.jpg",
    price: 5000,
    description: "Artisan made Sensitive skin moisturizer with restorative and conditioning ingredients that smoothens texturized skin, repairs the skin and slows down signs of aging ",
    contains: "Mango butter, Aloe vera gel, Glycerine, Green tea extract and Niacinamide ",
    usage: "apply on damp skin, after bathing",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 6,
    title: "Turmeric Soap",
    img: "img/turmeric soap.jpg",
    price: 3500,
    description: "Artisan made with anti-inflamatory and moisturizing plant derived ingredients to even-out your skin tone, boost skins' ability to generate collagen and helps fade discoloration caused by sun exposure.",
    contains: "Aloe Barbadensis(Aloe Vera), African Black Soap, Curcuma Longa(Turmeric), Santalum Album Linn(Sandalwood), Kojic",
    usage: "Apply on whole body for 5 minutes and rinse off with warm water.",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 7,
    title: "Me Radiance Lotion",
    img: "img/melanin radiance lotion.jpg",
    price: 6500,
    description: "Artisan made with skin conditioning and moisturizing ingredients to brighten the skin,soften and keep it hydrated",
    contains: "Rose hydrosol, Almond oil, Licorice extract, Carrot seed oil and Chamomile oil",
    usage: "apply on damp skin, after bathing",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    inCart: false,
    count: 0,
    total: 0
  },
  
  {
    id: 8,
    title: "Shea Glow Polish",
    img: "img/shea glow polish.jpg",
    price: 2500,
    description: "Artisan made with moisturizing and exfoliating naturally derived ingredients to gently exfoliate the skin and help restore skin radiance while protecting against free radicals.",
    contains: "Shea nut oil, Mango Butter, Cetearyl Olivate, Sorbitan Olivate(Olivem 1000 emulsifier), Ground Himalayan Salt and Collagen.",
    usage: "Massage desired quantity on body and rinse off with warm water.",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 9,
    title: "Radiance Face Milk",
    img: "img/radiant face milk.jpg",
    price: 2500,
    description: "Artisan made with plant essential oils to improve discoloration on the face and neck",
    contains: "Oragic aloe vera, Grapeseed oil, gluthathione and sandalwood oil",
    usage: "apply on face and neck area after bath",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 10,
    title: "Noono Kids Soap",
    img: "img/kids soap.jpg",
    price: 2500,
    description: "Carefully formulated with antibacterial plant extracts to gently cleanse the skin while protecting the skin from bacteral skin disorders ",
    contains: "African black soap, Organic aloe vera, sunflower oil, African camwood powder and Neem powder ",
    usage: "apply on whole body the rinse of with warm water",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 11,
    title: "Chiis Body Oil",
    img: "img/kids oil.jpg",
    price: 5000,
    description: "Carefully formulated with nourishing and protecting oils infused with sensitive skin loving essential oils to deeply moisturize and relieve dry skin conditions such as Eczema",
    contains: "Sunflower oil, Shea nut oil, Lavender essential oil and Mandarin essential oil ",
    usage: "apply on damp skin, immediately after bathing",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 12,
    title: "Kokoo Body butter",
    img: "img/kokoo body butter.jpg",
    price: 5000,
    description: "Carefully formulated with nourishing and protecting plant butters infused with essential oils for improving dry, textured skin on children and adults with very sensitive skin",
    contains: "Mango butter, Shea butter, Aloe vera, Sunflower oil with Mandarin and Lavender essential oils",
    usage: "apply on damp skin, immediately after bath",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 13,
    title: "Radiance Face Serum",
    img: "img/rf serum.jpg",
    price: 10000,
    description: "Artisan made with Jojoba and Argan oil infused with natural essential oils to gently lighten the face, soothe irritated skin and improve break outs",
    contains: "Jojoba Oil, Argan Oil, Frankincense Oil, Sandalwood Oil and Vitamin C.",
    usage: "Apply 2-3 drops on face and neck immediately after bath",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 25,
    title: "Face Mask",
    img: "img/face mask.jpg",
    price: 2500,
    description: "Deep cleansing masque made with exotic clays and plant extracts rich in nourishing vitamin C to gently lighten the face, tighten large pores, soothe irritated skin and improve skin texture.",
    contains: "French green clay, Bentonite clay, Baobab fruit powder, Sandalwood powder powder and Mullberry powder.",
    usage: "Step 1: Mix with desired activator and spread over face and neck (avoid sensitive eye area). Step 2: Allow mask to sit for 5-10minutes.  Step 3: When mask is dry and tight without being crusty, use damp hands to massage in circular motions to soften clay and gently exfoliate. Step 4: Massage until mask is creamy then wash off with warm water and pat dry with a clean towel.",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    inCart: false,
    count: 0,
    total: 0
  }

];

export const detailProduct = {
  id: 6,
  title: "Turmeric Soap",
  img: "img/turmeric soap.jpg",
  price: 3500,
  description: "one thing soap",
  contains: "some ingredients",
  usage: "apply on whole body",
  life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
  inCart: false,
  count: 0,
  total: 0
};

export const detailCat = {
  id: 14,
    title: "Premium Active Glow",
    img: "img/premium active glow set.jpg",
    price: 21000,
    description: "This collection is curated to clarify and unify your complexion, lighten the skin visibly up to two shades. Enjoy even toned skin with a flawless finish.",
    contains: "One turmeric soap, One shea glow polish, One light radiance lotion and One radiance face serum",
    usage: "Step 1: Massage desired quantity of body polish unto skin, leave for 5 minutes and then rinse off. Step 3: Apply soap unto skin before bath, then rinse off. Step 4: Apply face serum unto face and neck.  Step 3: Apply body lotion on damp skin.",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
  inCart: false,
  count: 0,
  total: 0
};
export const collectionDetail = {
  id: 13,
  title: "Premium Active Glow",
    img: "img/premium active glow set.jpg",
    price: 21000,
    description: "This collection is curated to clarify and unify your complexion, lighten the skin visibly up to two shades. Enjoy even toned skin with a flawless finish.",
    contains: "One turmeric soap, One shea glow polish, One light radiance lotion and One radiance face serum",
    usage: "Step 1: Massage desired quantity of body polish unto skin, leave for 5 minutes and then rinse off. Step 3: Apply soap unto skin before bath, then rinse off. Step 4: Apply face serum unto face and neck.  Step 3: Apply body lotion on damp skin.",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
  inCart: false,
  count: 0,
  total: 0
};

export const bestsellerProducts = [
{
  id: 14,
    title: "Lightening Set",
    img: "img/lightening set.jpg",
    price: 24000,
    description: "This collection is specifically created to clarify and unify your complexion, lighten the skin visibly up to two shades. Enjoy even toned skin with a flawless finish.",
    contains: "One soap, One lotion and One face milk. each set comes with a free shea glow polish",
    usage: "Step 1: Massage desired quantity of body polish unto skin, leave for 5 minutes and then rinse off. Step 3: Apply soap unto skin before bath, then rinse off. Step 4: Apply face milk unto face and neck.  Step 3: Apply body lotion on damp skin. EXFOLIATE WITH SHEA GLOW POLISH AT LEAST TWICE A WEEK.",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
  inCart: false,
  count: 0,
  total: 0
},
{
  id: 15,
  title: "Kids Care",
  img: "img/kids set.jpg",
  price: 12000,
  description: "Carefully put together to ensure that your children's skin is properly cleansed, moisturized and protected. this combination improves skin conditions such as dry skin and eczema",
  contains: "One noono kids soap, One kooko body butter and One chiis body oil",
  usage: "Step 1: Apply soap unto skin, then rinse off. Step 2: Apply body butter on damp skin.  Step 3: Apply body oil on hair and skin.",
  life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
  inCart: false,
  count: 0,
  total: 0
},
{
  id: 16,
  title: "Acne Set",
    img: "img/acne set.jpg",
    price: 14000,
    description: " This collection was put together to fight acne, improves discoloration on face and neck",
    contains: "One Detox face mask, One radiance face soap and One radiance face serum",
    usage: "Step 1: Mix half teaspoon of face mask with activator of choice. Apply generously on face and allow to dry but not crumbly, massage gently and then rinse off. Step 2: Massage soap as desired unto skin, then rinse off. Step 3: Apply face serum unto damp face and neck. BEST USED AT NIGHT!",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
  inCart: false,
  count: 0,
  total: 0
},
{
  id: 17,
  title: "Basic Glow",
  img: "img/basic glow set.jpg",
  price: 5000,
  description: "Specially curated to brighten dull skin by exfoliating the skin, keeping it moisturized and help to fade stretch marks",
  contains: "One shea glow polish and One shea glow oil",
  usage: "Step 1: Massage desired quantity of shea glow polish unto skin for 5minutes, then rinse off. Step 2: Apply shea glow oil on damp skin, immediately after exfoliating.  CAUTION:DO NOT Apply on your face if you have breakouts.",
  life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
  inCart: false,
  count: 0,
  total: 0
}
];
export const collections = [
  {
    id: 18,
    title: "Fresh Glow",
    img: "img/fresh glow set.jpg",
     price: 12000,
     description: "Specially curated to gently brighten face and body, soften the skin and improve skin radiance",
     contains: "One estelle black soap, One radiance lotion(melanin/caramel) and One radiance face milk",
    usage: "Step 1: Apply soap unto skin for 5minutes, then rinse off. Step 2: Apply face milk on face and neck.  Step 3: Apply lotion on body.",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 19,
    title: "Basic Glow",
    img: "img/basic glow set.jpg",
    price: 5000,
    description: "Specially curated to brighten dull skin by exfoliating the skin, keeping it moisturized and help to fade stretch marks",
    contains: "One shea glow polish and One shea glow oil",
    usage: "Step 1: Massage desired quantity of shea glow polish unto skin for 5minutes, then rinse off. Step 2: Apply shea glow oil on damp skin, immediately after exfoliating.  CAUTION:DO NOT Apply on your face if you have breakouts.",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 20,
    title: "Kids Care",
    img: "img/kids set.jpg",
    price: 12000,
    description: "Carefully put together to ensure that your children's skin is properly cleansed, moisturized and protected. this combination improves skin conditions such as dry skin and eczema",
    contains: "One noono kids soap, One kooko body butter and One chiis body oil",
    usage: "Step 1: Apply soap unto skin, then rinse off. Step 2: Apply body butter on damp skin.  Step 3: Apply body oil on hair and skin.",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 21,
    title: "Lightening Set",
    img: "img/lightening set.jpg",
    price: 24000,
    description: "This collection is specifically created to clarify and unify your complexion, lighten the skin visibly up to two shades. Enjoy even toned skin with a flawless finish.",
    contains: "One soap, One lotion and One face milk. each set comes with a free shea glow polish",
    usage: "Step 1: Massage desired quantity of body polish unto skin, leave for 5 minutes and then rinse off. Step 3: Apply soap unto skin before bath, then rinse off. Step 4: Apply face milk unto face and neck.  Step 3: Apply body lotion on damp skin. EXFOLIATE WITH SHEA GLOW POLISH AT LEAST TWICE A WEEK.",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 22,
    title: "Acne Face Set",
    img: "img/acne set.jpg",
    price: 11000,
    description: " This collection was put together to fight acne, improves discoloration on face and neck",
    contains: "One Detox face mask, One radiance face soap and One radiance face serum",
    usage: "Step 1: Mix half teaspoon of face mask with activator of choice. Apply generously on face and allow to dry but not crumbly, massage gently and then rinse off. Step 2: Massage soap as desired unto skin, then rinse off. Step 3: Clean face with a few drops of the toner on a cotton pad. Step 4: Apply face serum unto damp face and neck. BEST USED AT NIGHT!",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 23,
    title: "Active Glow",
    img: "img/active glow set.jpg",
    price: 12000,
    description: "This collection is designed for face and body lightening, it helps with hyperpigmentation and evens out skin tone",
    contains: "One turmeric soap, One light radiance lotion and One radiance face milk",
    usage: "Step 1: Apply soap unto skin, then rinse off. Step 2: Apply face milk on face and neck.  Step 3: Apply body lotion on damp skin.",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 24,
    title: "Repair Set",
    img: "img/anti aging set.jpg",
    price: 11000,
    description: "This collection was carefully put together with products made to repair damaged skin, smoothen wrinkled skin and delay the signs of aging ",
    contains: "One estelle black soap, One body souffle and One radiant face milk",
    usage: "Step 1: Apply soap unto skin, then rinse off. Step 2: Apply face milk on face and neck.  Step 3: Apply body lotion on damp skin.",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 25,
    title: "Radiance Face Set",
    img: "img/AFS cream.jpg",
    price: 9000,
    description: " This collection was put together to manage acne, improves discoloration on face and neck without interfering with your complexion",
    contains: "One Detox face mask, One hydrating toner, One radiance face soap and One radiance face milk",
    usage: "Step 1: Mix half teaspoon of face mask with activator of choice. Apply generously on face and allow to dry but not crumbly, massage gently and then rinse off. Step 2: Massage soap as desired unto skin, then rinse off. Step 3: Clean face with a few drops of the toner on a cotton pad. Step 4: Apply face milk unto damp face and neck. BEST USE A SUNSCREEN DURING THE DAY!",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    inCart: false,
    count: 0,
    total: 0
  }
  ];
export const lookup = {
  "Abuja": 1000,
  "Lagos": 1500,
  "Ibadan": 2000,
  "Portharcourt": 1500,
  "Benin": 1500,
  "Owerri": 2000,
  "Asaba": 2000,
  "Minna": 1500,
  "Jos": 2000,
  "Kaduna": 1500,
  "Aba":2000,
  "Uyo":2000,
  "Onitsha":2000,
  "Markudi":2000,
  "Calabar":2000,
  "Ikot":2000,
  "Warri":2000,
  "Enugu":2000,
  "Auchi":1500,
  "Akure":2000,
  "Kano":2000,
  "Mararaba":1500
}